Add option for use system libappimage
AppImage/AppImageUpdate pull request #188
Opened 2021-12-06 10:15 UTC by smarttowel

2022-01-12 11:27 UTC, TheAssassin requested changes
You'd have to make sure libappimage is installed in some way.

2022-01-12 11:27 UTC, TheAssassin commented on lib/CMakeLists.txt
> +endif()
Blank line removed at end of file for no apparent reason.

2022-01-15 00:40 UTC, TheAssassin reviewed
I am reworking the dependencies management at the moment. I will either merge your PR in the process, or write my own fix. libappimage is not the only external library, same goes for zsync2 for instance.

Thanks for bringing this up.

2022-01-15 00:40 UTC, TheAssassin commented on lib/CMakeLists.txt
> +    find_library(APPIMAGE_LIB appimage)
You should be able to find libappimage using `find_package`, since it generates an exported targets config.

2022-01-17 13:08 UTC, smarttowel commented
I agree about similar options for other external libraries, but I need only system libappimage at this moment.

2022-01-23 20:54 UTC, TheAssassin commented
Fixed in https://github.com/AppImage/AppImageUpdate/commit/7593d5aa9c1adfb450e79113fdb6e2f245233cf4. Just set `-DUSE_SYSTEM_LIBAPPIMAGE=ON`.

2022-01-23 20:54 UTC, closed without merging